kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts: &registry
  - hostPath: ./registry.d
    containerPath: /etc/containerd/registry.d
- role: worker
  extraMounts: *registry
networking:
  disableDefaultCNI: true
  kubeProxyMode: "none"
containerdConfigPatches:
- |-
  # Path manually-populated on each node, with `_default/hosts.toml` pointing to a cluster-local pull-through cache
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/registry.d"
kubeadmConfigPatches:
- |
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration
  metadata:
    name: parallel-image-pulls
  serializeImagePulls: false
  maxParallelImagePulls: 8
